/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import proyecto2estructuras.Arbol;
import proyecto2estructuras.usuarios.ListaUsuario;
import tablas.Tabla;

/**
 *
 * @author sebas
 */
public class Menuprincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menuprincipal.class.getName());
    static Arbol arbol; 
    static Tabla tabla;
    static ListaUsuario usuarios;

    /**
     * Creates new form menuprincipal
     */
    public Menuprincipal(Arbol a, Tabla t, ListaUsuario u) {
        initComponents();
        this.arbol= a;
        this.tabla= t;
        this.usuarios= u;
        this.setVisible(true);
        
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cargar = new javax.swing.JButton();
        cola1 = new javax.swing.JButton();
        cola2 = new javax.swing.JButton();
        crear = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        insertar = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setForeground(new java.awt.Color(33, 47, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargar.setBackground(new java.awt.Color(51, 255, 204));
        cargar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cargar.setText("Cargar");
        cargar.addActionListener(this::cargarActionPerformed);
        jPanel1.add(cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 180, 70));

        cola1.setBackground(new java.awt.Color(51, 255, 204));
        cola1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cola1.setText("Cola De Impresion");
        cola1.addActionListener(this::cola1ActionPerformed);
        jPanel1.add(cola1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 180, 70));

        cola2.setBackground(new java.awt.Color(51, 255, 204));
        cola2.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        cola2.setText("Cola De Impresion Arbol");
        cola2.addActionListener(this::cola2ActionPerformed);
        jPanel1.add(cola2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 200, 70));

        crear.setBackground(new java.awt.Color(51, 255, 204));
        crear.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        crear.setText("Crear Documentos");
        crear.addActionListener(this::crearActionPerformed);
        jPanel1.add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 180, 70));

        eliminar.setBackground(new java.awt.Color(51, 255, 204));
        eliminar.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(this::eliminarActionPerformed);
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 180, 70));

        insertar.setBackground(new java.awt.Color(51, 255, 204));
        insertar.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        insertar.setText("Insertar");
        insertar.addActionListener(this::insertarActionPerformed);
        jPanel1.add(insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 180, 70));

        jButton8.setBackground(new java.awt.Color(51, 255, 204));
        jButton8.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jButton8.setText("Usuarios");
        jButton8.addActionListener(this::jButton8ActionPerformed);
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 180, 70));

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 360, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
     // TODO add your handling code here:
     Cargar m = new Cargar(arbol,tabla,usuarios);
     this.dispose();
     
    }//GEN-LAST:event_cargarActionPerformed

    private void cola1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cola1ActionPerformed
        // TODO add your handling code here:
        Coladeimpresion m = new Coladeimpresion(arbol,tabla,usuarios);
        this.dispose();
    }//GEN-LAST:event_cola1ActionPerformed

    private void cola2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cola2ActionPerformed
Coladeimpresionarbol m = new Coladeimpresionarbol(arbol,tabla,usuarios);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cola2ActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:
        Creardocumentos m = new Creardocumentos(arbol,tabla,usuarios);
        this.dispose();
    }//GEN-LAST:event_crearActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        Eliminar m = new Eliminar(arbol,tabla,usuarios);
        this.dispose();
    }//GEN-LAST:event_eliminarActionPerformed

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed
        // TODO add your handling code here:
        Insertar m = new Insertar(arbol,tabla,usuarios);
        this.dispose();
    }//GEN-LAST:event_insertarActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Usuarios m = new Usuarios(arbol,tabla,usuarios);
        this.dispose();
        
                
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menuprincipal(arbol, tabla, usuarios).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargar;
    private javax.swing.JButton cola1;
    private javax.swing.JButton cola2;
    private javax.swing.JButton crear;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton insertar;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
